# Generated by Django 3.0b1 on 2019-10-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresses', models.CharField(blank=True, max_length=36, null=True, verbose_name='Logradouro')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='State')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complement')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='CEP')),
                ('neighborhood', models.CharField(blank=True, max_length=72, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=72, null=True, verbose_name='Cidade')),
            ],
        ),
    ]
