# Generated by Django 3.0b1 on 2019-10-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='bairro_nu_ini',
            field=models.CharField(blank=True, max_length=72, null=True, verbose_name='bairro_nu_ini'),
        ),
        migrations.AddField(
            model_name='addresses',
            name='loc_nu',
            field=models.CharField(blank=True, max_length=72, null=True, verbose_name='loc_nu'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='city',
            field=models.CharField(blank=True, max_length=72, null=True, verbose_name='Cidade'),
        ),
    ]
